language: node_js
node_js:
  - "5"
  - "6"
sudo: false
script: "npm test"

before_install:
  # since it's a peerdependency it isn't pulled in unless it's installed as a dependency
  npm install react react-dom
